title: Shaun Tran
description: Bachelors in Applied Mathematics, Emphasis on Computational & Data Sciences | Aspiring Data Scientist
logo: assets/img/head.jpg
#show_downloads: true
theme: jekyll-theme-minimal
